// <auto-generated />
using System;
using Base;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BuiltOnRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("KingdomId");

                    b.HasIndex("TileId")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.Buildings.BuildingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmyCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("BaseYieldFood")
                        .HasColumnType("integer");

                    b.Property<int>("BaseYieldGold")
                        .HasColumnType("integer");

                    b.Property<int>("BaseYieldMana")
                        .HasColumnType("integer");

                    b.Property<int>("BaseYieldStone")
                        .HasColumnType("integer");

                    b.Property<int>("BaseYieldWood")
                        .HasColumnType("integer");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CostFood")
                        .HasColumnType("integer");

                    b.Property<int>("CostGold")
                        .HasColumnType("integer");

                    b.Property<int>("CostMana")
                        .HasColumnType("integer");

                    b.Property<int>("CostStone")
                        .HasColumnType("integer");

                    b.Property<int>("CostWood")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UnlockedByBuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnlockedByBuildingTypeId");

                    b.ToTable("BuildingTypes");
                });

            modelBuilder.Entity("Domain.Factions.FactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionPointModifier")
                        .HasColumnType("integer");

                    b.Property<decimal>("AttackModifier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BuildingCostModifier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChipDamageModifier")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("HPModifier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HealRateModifier")
                        .HasColumnType("numeric");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("InitiativeModifier")
                        .HasColumnType("numeric");

                    b.Property<string>("Lore")
                        .HasColumnType("text");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("ResourceProductionModifier")
                        .HasColumnType("numeric");

                    b.Property<int>("StartingBonusAmount")
                        .HasColumnType("integer");

                    b.Property<string>("StartingBonusResource")
                        .HasColumnType("text");

                    b.Property<decimal>("TrainingCostModifier")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FactionTypes");
                });

            modelBuilder.Entity("Domain.Game.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseActionPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentTurnKingdomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HealPercent")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LobbyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MapHeight")
                        .HasColumnType("integer");

                    b.Property<int>("MapWidth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RemainingActionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SlotOutcomeWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SpinCostGold")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TurnDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TurnTimeLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WinnerKingdomId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTurnKingdomId");

                    b.HasIndex("HostUserId");

                    b.HasIndex("LobbyCode")
                        .IsUnique();

                    b.HasIndex("WinnerKingdomId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Domain.Game.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ResourceEffect")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Domain.Game.Kingdom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DefeatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("FactionTypeId");

                    b.HasIndex("GameId");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("Domain.Game.TurnLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("GameId", "KingdomId");

                    b.HasIndex("GameId", "RoundNumber");

                    b.ToTable("TurnLogs");
                });

            modelBuilder.Entity("Domain.Map.TerrainType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("MapColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResourceBonusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ResourceMultiplier")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TerrainTypes");
                });

            modelBuilder.Entity("Domain.Map.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CoordQ")
                        .HasColumnType("integer");

                    b.Property<int>("CoordR")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCastle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TerrainTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("TerrainTypeId");

                    b.HasIndex("GameId", "CoordQ", "CoordR")
                        .IsUnique();

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Domain.Military.Army", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArmyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedOnRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<Guid>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArmyTypeId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("KingdomId");

                    b.HasIndex("TileId");

                    b.ToTable("Armies");
                });

            modelBuilder.Entity("Domain.Military.ArmyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChipDamageRangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChipDamageRangeMin")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DamageRangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DamageRangeMin")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RequiredBuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SituationalBonusCondition")
                        .HasColumnType("text");

                    b.Property<string>("SituationalBonusStat")
                        .HasColumnType("text");

                    b.Property<decimal?>("SituationalBonusValue")
                        .HasColumnType("numeric");

                    b.Property<int>("TrainingCostFood")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCostGold")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCostMana")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCostStone")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpkeepFood")
                        .HasColumnType("integer");

                    b.Property<int>("UpkeepGold")
                        .HasColumnType("integer");

                    b.Property<int>("UpkeepMana")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequiredBuildingTypeId");

                    b.ToTable("ArmyTypes");
                });

            modelBuilder.Entity("Domain.Military.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerKingdomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerTileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenderKingdomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefenderTileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TileCapturedFromKingdomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TileCapturedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttackerKingdomId");

                    b.HasIndex("AttackerTileId");

                    b.HasIndex("DefenderKingdomId");

                    b.HasIndex("DefenderTileId");

                    b.HasIndex("GameId");

                    b.HasIndex("TileCapturedFromKingdomId");

                    b.HasIndex("TileCapturedId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("Domain.Military.BattleRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmyDestroyedId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttackerArmyHPAfter")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttackerArmyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AttackerInitiativeChance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChipDamageDealt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderArmyHPAfter")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefenderArmyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefenderInitiativeChance")
                        .HasColumnType("numeric");

                    b.Property<string>("InitiativeWinner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattleId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("BattleRounds");
                });

            modelBuilder.Entity("Domain.Military.DeclaredAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerKingdomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AttackerLineupConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("AttackerSelectedArmyIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenderKingdomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DefenderLineupConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("DefenderSelectedArmyIds")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiskedTileId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetTileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttackerKingdomId");

                    b.HasIndex("DefenderKingdomId");

                    b.HasIndex("GameId");

                    b.HasIndex("RiskedTileId");

                    b.HasIndex("TargetTileId");

                    b.ToTable("DeclaredAttacks");
                });

            modelBuilder.Entity("Domain.Resources.KingdomResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId", "ResourceType")
                        .IsUnique();

                    b.ToTable("KingdomResources");
                });

            modelBuilder.Entity("Infrastructure.Identity.AppRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreviousExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Buildings.Building", b =>
                {
                    b.HasOne("Domain.Buildings.BuildingType", "BuildingType")
                        .WithMany("Buildings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "Kingdom")
                        .WithMany("Buildings")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "Tile")
                        .WithMany("Buildings")
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("Kingdom");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("Domain.Buildings.BuildingType", b =>
                {
                    b.HasOne("Domain.Buildings.BuildingType", "UnlockedByBuildingType")
                        .WithMany()
                        .HasForeignKey("UnlockedByBuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UnlockedByBuildingType");
                });

            modelBuilder.Entity("Domain.Game.Game", b =>
                {
                    b.HasOne("Domain.Game.Kingdom", "CurrentTurnKingdom")
                        .WithMany()
                        .HasForeignKey("CurrentTurnKingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Game.Kingdom", "WinnerKingdom")
                        .WithMany()
                        .HasForeignKey("WinnerKingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentTurnKingdom");

                    b.Navigation("WinnerKingdom");
                });

            modelBuilder.Entity("Domain.Game.Kingdom", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Factions.FactionType", "FactionType")
                        .WithMany("Kingdoms")
                        .HasForeignKey("FactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Game.Game", "Game")
                        .WithMany("Kingdoms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactionType");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Game.TurnLog", b =>
                {
                    b.HasOne("Domain.Game.Game", "Game")
                        .WithMany("TurnLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "Kingdom")
                        .WithMany("TurnLogs")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Domain.Map.Tile", b =>
                {
                    b.HasOne("Domain.Game.Game", "Game")
                        .WithMany("Tiles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "Kingdom")
                        .WithMany("Tiles")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Map.TerrainType", "TerrainType")
                        .WithMany("Tiles")
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Kingdom");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("Domain.Military.Army", b =>
                {
                    b.HasOne("Domain.Military.ArmyType", "ArmyType")
                        .WithMany("Armies")
                        .HasForeignKey("ArmyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Buildings.Building", "Building")
                        .WithMany("Armies")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "Kingdom")
                        .WithMany("Armies")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", null)
                        .WithMany("Armies")
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArmyType");

                    b.Navigation("Building");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Domain.Military.ArmyType", b =>
                {
                    b.HasOne("Domain.Buildings.BuildingType", "RequiredBuildingType")
                        .WithMany()
                        .HasForeignKey("RequiredBuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredBuildingType");
                });

            modelBuilder.Entity("Domain.Military.Battle", b =>
                {
                    b.HasOne("Domain.Game.Kingdom", "AttackerKingdom")
                        .WithMany()
                        .HasForeignKey("AttackerKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "AttackerTile")
                        .WithMany()
                        .HasForeignKey("AttackerTileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "DefenderKingdom")
                        .WithMany()
                        .HasForeignKey("DefenderKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "DefenderTile")
                        .WithMany()
                        .HasForeignKey("DefenderTileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Game", "Game")
                        .WithMany("Battles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "TileCapturedFromKingdom")
                        .WithMany()
                        .HasForeignKey("TileCapturedFromKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "TileCaptured")
                        .WithMany()
                        .HasForeignKey("TileCapturedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackerKingdom");

                    b.Navigation("AttackerTile");

                    b.Navigation("DefenderKingdom");

                    b.Navigation("DefenderTile");

                    b.Navigation("Game");

                    b.Navigation("TileCaptured");

                    b.Navigation("TileCapturedFromKingdom");
                });

            modelBuilder.Entity("Domain.Military.BattleRound", b =>
                {
                    b.HasOne("Domain.Military.Battle", "Battle")
                        .WithMany("BattleRounds")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");
                });

            modelBuilder.Entity("Domain.Military.DeclaredAttack", b =>
                {
                    b.HasOne("Domain.Game.Kingdom", "AttackerKingdom")
                        .WithMany()
                        .HasForeignKey("AttackerKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Kingdom", "DefenderKingdom")
                        .WithMany()
                        .HasForeignKey("DefenderKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Game.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "RiskedTile")
                        .WithMany()
                        .HasForeignKey("RiskedTileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Map.Tile", "TargetTile")
                        .WithMany()
                        .HasForeignKey("TargetTileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackerKingdom");

                    b.Navigation("DefenderKingdom");

                    b.Navigation("Game");

                    b.Navigation("RiskedTile");

                    b.Navigation("TargetTile");
                });

            modelBuilder.Entity("Domain.Resources.KingdomResource", b =>
                {
                    b.HasOne("Domain.Game.Kingdom", "Kingdom")
                        .WithMany("Resources")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Infrastructure.Identity.AppRefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Buildings.Building", b =>
                {
                    b.Navigation("Armies");
                });

            modelBuilder.Entity("Domain.Buildings.BuildingType", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Domain.Factions.FactionType", b =>
                {
                    b.Navigation("Kingdoms");
                });

            modelBuilder.Entity("Domain.Game.Game", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Kingdoms");

                    b.Navigation("Tiles");

                    b.Navigation("TurnLogs");
                });

            modelBuilder.Entity("Domain.Game.Kingdom", b =>
                {
                    b.Navigation("Armies");

                    b.Navigation("Buildings");

                    b.Navigation("Resources");

                    b.Navigation("Tiles");

                    b.Navigation("TurnLogs");
                });

            modelBuilder.Entity("Domain.Map.TerrainType", b =>
                {
                    b.Navigation("Tiles");
                });

            modelBuilder.Entity("Domain.Map.Tile", b =>
                {
                    b.Navigation("Armies");

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Domain.Military.ArmyType", b =>
                {
                    b.Navigation("Armies");
                });

            modelBuilder.Entity("Domain.Military.Battle", b =>
                {
                    b.Navigation("BattleRounds");
                });

            modelBuilder.Entity("Infrastructure.Identity.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
